# 核心任务
- name: MySQL
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'mysql_selection'
      prompt: "\nPlease choose the number for MySQL version [ 1/2/3/4] \n\n
      1: MySQL5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL5.6(only for CentOS7.x, AmazonLinux, Ubuntu16.04 )\n
      3: MySQL5.7\n
      4: MySQL8.0\n"
      private: no
      default: 3

    - name: 'remote_selection'
      prompt: "\nDo you want to enable MySQL remote connection? [ 1/2 ] \n\n
      1: Enable remote connection(default)\n
      2: Disable remote connection\n"
      private: no
      default: 1

    - name: 'phpmyadmin_selection'
      prompt: "\nDo you want to install phpMyAdmin of Docker? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

  vars:
    mysql_select:
      '1': '5.5'
      '2': '5.6'
      '3': '5.7'
      '4': '8.0'
    mysql_version: "{{mysql_select[mysql_selection]}}" 

    phpmyadmin_select:
      '1': True
      'y': True
      '2': ''
      'n': ''

    remote_select:
      '1': True
      '2': False
      
    
    phpmyadmin_install_docker: "{{phpmyadmin_select[phpmyadmin_selection]}}" 
    mysql_remote: "{{remote_select[remote_selection]}}" or "{{phpmyadmin_select[phpmyadmin_selection]}}" 
  
  roles:
   - {role: role_common, tags: "role_common"}   
   - {role: role_cloud, tags: "role_cloud"}
   - {role: role_mysql, tags: "role_mysql"}
   - {role: role_docker, tags: "role_docker", when: phpmyadmin_install_docker}
   - {role: role_docker_phpmyadmin, tags: "role_docker_phpmyadmin", when: phpmyadmin_install_docker}
   - {role: role_init_password, tags: "role_init_password"}
   - {role: role_end, tags: "role_end"} 
