# 核心任务
- name: MySQL
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: 'mysql_type_selection'
      prompt: "\nPlease Select the type of database to install [ 1/2] \n\n
      1: Docker install\n
      2: Package install\n"
      private: no
      default: 1

    - name: 'mysql_version_selection'
      prompt: "\nPlease choose the number for MySQL version [ 1/2/3/4] \n\n
      1: MySQL5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL5.6(Support all)\n
      3: MySQL5.7(Support all)\n
      4: MySQL8.0(Support all)\n"
      private: no
      default: 3

    - name: 'remote_selection'
      prompt: "\nDo you want to enable MySQL remote connection? [ 1/2 ] \n\n
      1: Enable remote connection(default)\n
      2: Disable remote connection\n"
      private: no
      default: 1

    - name: 'phpmyadmin_selection'
      prompt: "\nDo you want to install phpMyAdmin of Docker? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

  vars:
    mysql_version_select:
      '1': '5.5'
      '2': '5.6'
      '3': '5.7'
      '4': '8.0'
    mysql_version: "{{mysql_version_select[mysql_version_selection]}}" 

    mysql_type_select:
      '1': True
      'y': True
      '2': False
      'n': False
    mysql_docker: "{{mysql_type_select[mysql_type_selection]}}"

    phpmyadmin_select:
      '1': True
      'y': True
      '2': ''
      'n': ''

    remote_select:
      '1': True
      '2': False
      
    phpmyadmin_install_docker: "{{phpmyadmin_select[phpmyadmin_selection]}}" 
    mysql_remote: "{{remote_select[remote_selection]}} or {{phpmyadmin_select[phpmyadmin_selection]}}" 

  pre_tasks:
    - include_vars: vars/docker.yml
      when: mysql_docker
    - include_vars: vars/main.yml
      when: not mysql_docker
    - debug: 
        msg: MySql{{mysql_version}} will be install, Container version of MySQL is {{mysql_docker}}

  roles:
   - {role: role_common, tags: "role_common"}   
   - {role: role_cloud, tags: "role_cloud"}
   - {role: role_mysql, tags: "role_mysql"}
   - {role: role_docker, tags: "role_docker", when: phpmyadmin_install_docker}
   - {role: role_init, tags: "role_init"}
   - {role: role_preend, tags: "role_preend"}
   - {role: role_end, tags: "role_end"} 
