# 本地同步公共Roles
- name: mysql
  hosts: local
  connection: local
  gather_facts: False
  pre_tasks:
    - name: Set Git Repo
      shell: |
        git init
        git config core.sparsecheckout true
        git remote add origin https://github.com/Websoft9/ansible-roles.git
        echo {{ item }} >> .git/info/sparse-checkout
      args:
        chdir: roles
      with_items:
        - "{{ public_roles }}"

    - name: GET Public Roles
      git:
        repo: https://github.com/Websoft9/ansible-roles.git
        dest: roles
        clone: no

    - name: Delete .git
      file:
        path: roles/.git
        state: absent

# 服务器前置任务(ubuntu使用)
- name: mysql
  hosts: mysql
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
  ignore_errors: yes


# 核心任务

- name: mysql
  hosts: mysql
  become: yes
  become_method: sudo
  roles:
    - { role: common , tags: "common"}  
    - {role: mysql, tags: "mysql"}
    - {role: random, tags: "random"}
    - {role: docker, tags: "docker"}
    - {role: docker_phpmyadmin, tags: "docker_phpmyadmin"}




    


                                                                                                    